#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=5g
#SBATCH -t 5-00:00:00
#SBATCH --job-name NFmaster

reads=$1
reference=$2
output=$3
structure1=$4
structure2=$5

module load NextFlow/19.10.0

nextflow \
-c ~/CODE/core/workflows/umi/umi_nextflow.config \
run ~/CODE/core/workflows/umi/umi_preprocess.nf \
-with-trace \
-with-timeline nf_umi-consensus_timeline.htm \
-with-report nf_umi-consensus_report.htm \
--reads /usr/share/sequencing/projects/307/raw_data \
--reference /usr/share/sequencing/references/homo_sapiens/hg19/gatk_references/hg19_v0_Homo_sapiens_assembly19.fasta \
--output_dir /usr/share/sequencing/projects/307/analysis/test_nextflow \
--read_structure1 7M1S+T \
--read_structure2 7M1S+T
