---
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r, include=FALSE}
res <- read_tsv(results, col_names=FALSE)
  title <- gsub("_blast_results.txt", "", results)

if(dim(res)[1]==0){
  checkPos <- FALSE
  checkNeg <- TRUE
} else {
  checkPos <- TRUE
  checkNeg <- FALSE
  names(res) <- c("qseqid", "sseqid", "sgi", "qstart", "qend", "sstart", "send", "pident", "mismatch", "nident", "evalue")

  table <- res %>%
    filter(pident == 100) %>%
    mutate(gene = sub("^(.*)-.*$", "\\1", sseqid),
            strain = sub("^.*-(.*)$", "\\1", sseqid)
          ) %>%
    group_by(gene, strain) %>%
    summarise( abs = n()) %>%
    mutate(freq = (abs / sum(abs)) * 100)
}



```




## Abundance table for `r title`

```{r, eval=checkNeg, results='asis', echo=FALSE}
cat('Results for this sample are negative, i.e. no reads have been matched to any sequence in the database.\n')
```


```{r, results='asis', echo=FALSE, eval=checkPos}
library(pander)
pander(table)
```


## Abundance plot for `r title`


```{r, eval=checkNeg, results='asis', echo=FALSE}
cat('Results for this sample are negative, i.e. no reads have been matched to any sequence in the database.\n')
```


```{r, echo=FALSE, eval=checkPos}
strains = unique(table$strain)[order(unique(table$strain))]
table %>%
  mutate(frequency = ifelse(strain==strains[1], freq, freq * -1)) %>%
  ggplot(aes(y=frequency, x=gene, fill=strain))+
  geom_bar(stat = "identity")
```

